### ISSUE TITLE
Error while running test-rendering.py

### ISSUE THREAD

**Issue by devendrachaplot** [facebookresearch/House3D#20]
I get an error when I try to run the python tests:
`python test-rendering.py house.obj`
```
[EGL] Detected 2 devices. Using device 0
error: ERROR::FRAMEBUFFER: Framebuffer is not complete!
```
I read the common issues, I am not running any other renderer.

I am running House3D inside a docker.

**Comment by ppwwyyxx** [comment]
Just to confirm, you have this error even though `objview-offline.bin` can work and writes an image correctly?

**Comment by devendrachaplot** [comment]
Yes `objview-offline.bin` is working fine.

**Comment by ppwwyyxx** [comment]
Does this work outside the docker on the same machine?

**Comment by devendrachaplot** [comment]
Yes, it does work outside the docker.

**Comment by devendrachaplot** [comment]
Seems like the LD_LIBRARY_PATH was reset for some reason. It works when I added the path to libglvnd to LD_LIBRARY_PATH. Thanks for the help!
