### ISSUE TITLE
make error: cannot find -lEGL but it has been installed

### ISSUE THREAD

**Issue by nina124** [facebookresearch/House3D#21]
Hi, I met the following error when building renderer
> [bin] objview-offline.bin ...
[bin] objview-suncg.bin ...
[bin] objview.bin ...
[bin] test-rectangle.bin ...
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
Makefile:52: recipe for target 'objview-offline.bin' failed
make: *** [objview-offline.bin] Error 1
make: *** Waiting for unfinished jobs....
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
Makefile:52: recipe for target 'objview-suncg.bin' failed
make: *** [objview-suncg.bin] Error 1
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
Makefile:52: recipe for target 'objview.bin' failed
make: *** [objview.bin] Error 1
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
Makefile:52: recipe for target 'test-rectangle.bin' failed
make: *** [test-rectangle.bin] Error 1
make: *** wait: No child processes.  Stop.

It shows `/usr/bin/ld: cannot find -lEGL`, but it has been installed.
Here's the output of debug_build.sh
    
    PATH:
    /opt/intel/compilers_and_libraries_2018.0.128/linux/bin/intel64:/opt/intel/compilers_and_libraries_2018.0.128/linux/mpi/intel64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda/bin

    CPATH:
    /opt/intel/compilers_and_libraries_2018.0.128/linux/ipp/include:/opt/intel/compilers_and_libraries_2018.0.128/linux/mkl/include:/opt/intel/compilers_and_libraries_2018.0.128/linux/pstl/include:/opt/intel/compilers_and_libraries_2018.0.128/linux/tbb/include:/opt/intel/compilers_and_libraries_2018.0.128/linux/tbb/include:/opt/intel/compilers_and_libraries_2018.0.128/linux/daal/include

    PKG_CONFIG_PATH:

    LIBRARY_PATH:
    /opt/intel/compilers_and_libraries_2018.0.128/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2018.0.128/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.0.128/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2018.0.128/linux/mpi/mic/lib:/opt/intel/compilers_and_libraries_2018.0.128/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2018.0.128/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.0.128/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.0.128/linux/tbb/lib/intel64/gcc4.7:/opt/intel/compilers_and_libraries_2018.0.128/linux/tbb/lib/intel64/gcc4.7:/opt/intel/debugger_2018/iga/lib:/opt/intel/debugger_2018/libipt/intel64/lib:/opt/intel/compilers_and_libraries_2018.0.128/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.0.128/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/usr/local/cuda/lib64:/usr/local/lib:/usr/lib

    LD_LIBRARY_PATH:
    /opt/intel/compilers_and_libraries_2018.0.128/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2018.0.128/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.0.128/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2018.0.128/linux/mpi/mic/lib:/opt/intel/compilers_and_libraries_2018.0.128/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2018.0.128/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.0.128/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.0.128/linux/tbb/lib/intel64/gcc4.7:/opt/intel/compilers_and_libraries_2018.0.128/linux/tbb/lib/intel64/gcc4.7:/opt/intel/debugger_2018/iga/lib:/opt/intel/debugger_2018/libipt/intel64/lib:/opt/intel/compilers_and_libraries_2018.0.128/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.0.128/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/usr/local/cuda/lib64:/usr/local/lib:/usr/local/lib:/usr/local/lib

    + pkg-config --cflags --libs glew
    -I/usr/include/libdrm -lGLEW -lGLU -lGL
    + pkg-config --cflags --libs glfw3
    -I/usr/include/libdrm -lglfw
    + '[' '!' '' ']'
    + pkg-config --cflags --libs libglvnd
    Package libglvnd was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libglvnd.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libglvnd' found
    + pkg-config --cflags --libs egl
    -I/usr/include/libdrm -lEGL
    + which find
    /usr/bin/find
    + which pkg-config
    /usr/bin/pkg-config
    + which python-config
    /usr/bin/python-config
    + python-config --includes --ldflags
    -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7
    -L/usr/lib/python2.7/config-x86_64-linux-gnu -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
    + '[' ']'
    + g++ --version
    g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    + '[' -f ../House3D/objrender.so ']'
    + '[' -f objview.bin ']'

**Comment by ppwwyyxx** [comment]
But what do you mean by "it has been installed"?
You need files like "EGL.so*" which usually comes with the driver. Add their path to LD_LIBRARY_PATH then the build should work.

**Comment by nina124** [comment]
Sorry to bother you.
I just found the problem. On my computer, the soft link to libEGL.so is broken. After fixing it, it could build.
