### ISSUE TITLE
Multiple agents

### ISSUE THREAD

**Issue by sumitsk** [facebookresearch/House3D#23]
Is it possible to have multiple agents in the environment and control them independently?

**Comment by ppwwyyxx** [comment]
Thanks for the interest. For now this is not supported. But you can start multiple instances of environment on the same house, and control these environments separately.

**Comment by sumitsk** [comment]
But those multiple instances will be independent of each other. In other words, agent in one instance will be completely unaware of the second agent in a separate instance. Is that correct?

**Comment by ppwwyyxx** [comment]
Yes.
