### ISSUE TITLE
How to generate another types of questions?

### ISSUE THREAD

**Issue by willanxywc** [facebookresearch/House3D#24]
How to generate another 5 types of questions except for the EQA v1?

**Comment by abhshkdz** [comment]
Hey, EQA v1 (location, color, proposition) + v2 (existence, logical, count, room_count, distance comparison) questions are available [here](https://www.dropbox.com/s/98iv25dobuan3i6/eqa_v2.json?dl=0). We're working on releasing the data generation code soon.

**Comment by abhshkdz** [comment]
Yes
