### ISSUE TITLE
Starting inside of houses

### ISSUE THREAD

**Issue by mfuntowicz** [facebookresearch/House3D#26]
Hi, 

I'm working on an experiment where I have to start inside of the houses but I'm currently not able to find an easy way of doing this.

Do you have some hints/advice for achieving this ?

Thanks in advance, 
Morgan

**Comment by ppwwyyxx** [comment]
From the `house.json` file that comes with each house in SUNCG, you can parse the coordinates of each room and set your agent to a location inside some rooms.

We provided some similar features in `House`: `House.getRandomLocationForRoom` returns an unoccupied SUNCG coordinate inside a given room.

**Comment by mfuntowicz** [comment]
Thanks ! Exactly what I needed :)
