### ISSUE TITLE
from House3D import objrender

### ISSUE THREAD

**Issue by xaxala777** [facebookresearch/House3D#27]
excuse me i can't find the objrender module. how can i import it from house3D?

**Comment by ppwwyyxx** [comment]
Hi! Please see our instructions: https://github.com/facebookresearch/House3D/blob/master/INSTRUCTION.md#installation

**Comment by xaxala777** [comment]
can i perform this project in windows system?

**Comment by ppwwyyxx** [comment]
Sorry but we have no plans for windows support.
