### ISSUE TITLE
How to change bit-depth in depth

### ISSUE THREAD

**Issue by DrifterFun** [facebookresearch/House3D#28]
Hi!
I am using House3D in my study. I found that depth map is story in `unint8`. I want to know how can I change bit-depth in depth map (for example `unint16`)?

And I also want to ask what is the distance between camera and objects if a pixel is `255` in depth map.

**Comment by ppwwyyxx** [comment]
Thanks for your interest! Your question is answered by this part of docs in the code:
https://github.com/facebookresearch/House3D/blob/bfc6b49970ea1e8d143ada93005b7d7fd1fb70bf/renderer/suncg/render.hh#L63-L79

Inverse depth may provide better resolution close to the camera. These two depth modes are the only two supported. You can also find more information in #15.

**Comment by DrifterFun** [comment]
Thx for you help!

**Comment by DrifterFun** [comment]
I am sorry to bother you again.
I am wondering if this means the value in SUNCG coordinate?
```
pixel / 255.0 * 20.0 is the true depth in meters.
```

**Comment by ppwwyyxx** [comment]
Yes. This distance has the same unit as the `house.obj` file.
