### ISSUE TITLE
objrender

### ISSUE THREAD

**Issue by xaxala777** [facebookresearch/House3D#29]
sorry to raise this question again, but I still can't find module "objrender". When I run python test-rendering.py, it always shows "ImportError: No module named objrender". I have read the usage instructions for several times still can't find a solution. would you please provide the solution in detail? it will be much appreciated.

**Comment by ppwwyyxx** [comment]
If you're using nvidia GPU and linux, you can use our docker file which contains the entire build process (only several lines actually).

If you cannot use docker for some reason and want to debug your issues, please paste what you did and what you observed in full. Otherwise it's hard to tell what goes wrong.

**Comment by xaxala777** [comment]
here is my code running in terminal:
### 
xaxala777@ubuntu:~$ cd /mnt/hgfs/pycharm/House3D-example-data/tests

xaxala777@ubuntu:/mnt/hgfs/pycharm/House3D-example-data/tests$ export PYTHONPATH=$PYTHONPATH:/mnt/hgfs/pycharm/House3D-example-data

xaxala777@ubuntu:/mnt/hgfs/pycharm/House3D-example-data/tests$ python test-rendering.py

Traceback (most recent call last):
  File "test-rendering.py", line 15, in <module>
    from House3D import objrender, create_default_config
  File "/mnt/hgfs/pycharm/House3D-example-data/House3D/__init__.py", line 6, in <module>
    from .core import Environment, MultiHouseEnv
  File "/mnt/hgfs/pycharm/House3D-example-data/House3D/core.py", line 17, in <module>
    from .objrender import RenderMode
ImportError: No module named objrender
### 
In House3D folder I can't find any file related to objrender. so I don't know how to figure that out.

**Comment by ppwwyyxx** [comment]
Then you have missed (or failed) the first step: compiling the renderer: https://github.com/facebookresearch/House3D/tree/master/renderer
If the compilation of the renderer succeed, it will produce `objrender.so` under House3D.

If you encounter errors while building the renderer, please include details following the [trouble shooting guide](https://github.com/facebookresearch/House3D/tree/master/renderer#trouble-shooting)
