### ISSUE TITLE
which part of the code is implementing the function of proposing House3D?

### ISSUE THREAD

**Issue by whk1994** [facebookresearch/House3D#30]
Hello,i am sorry that my computer skill is not very good, I want to know which part of the code is implementing the function of proposing House3D? Do I need to download the SUNCG database?

**Comment by ppwwyyxx** [comment]
Yes you need to download SUNCG and prepare it per the [instructions](https://github.com/facebookresearch/House3D/blob/master/INSTRUCTION.md#suncg-dataset).
