### ISSUE TITLE
bug in gen_2dmap

### ISSUE THREAD

**Issue by danielgordon10** [facebookresearch/House3D#31]
https://github.com/facebookresearch/House3D/blob/master/House3D/core.py#L172

cv2.circle does not return an image, it returns none. This line should be:
`cv2.circle(locMap, (x, y), int(rad), (255, 50, 50), thickness=-1)`

**Comment by ppwwyyxx** [comment]
It returns an image in opencv3: https://docs.opencv.org/3.0-beta/modules/imgproc/doc/drawing_functions.html#circle

I'll update the documentation to reflect this.
