### ISSUE TITLE
Failed to get color for shape when test-rendering

### ISSUE THREAD

**Issue by ZhuFengdaaa** [facebookresearch/House3D#38]
I use the example house 3d data to test-rendering. 
```
$ python test-rendering.py ../../house/05cac5f7fdd5f8138234164e76a97383/house.obj
``` 
But get the error log like
```
[get_color_by_shape_name@scene.cc:204] Failed to get color for shape Model#85
``` 
Image output by test-rendering.py like this ![mode=0.png](https://image.ibb.co/fahUT9/mode_0.png)

**Comment by ppwwyyxx** [comment]
The rendering looks right. 
But it should be able to parse the colors. Have you made any changes to the csv files in the project? Is there only one line of such error or more?

**Comment by RAWCHY** [comment]
did it work?
