### ISSUE TITLE
Dockerfile pip3 install -e . returned a non-zero code: 1

### ISSUE THREAD

**Issue by gengmujian10** [facebookresearch/House3D#39]
This is the first time I use docker, hoping to build the House3D envs.
But I meet this problem at the final stage.
I do not know how to solve this problem...
I use ubuntu 14.04 system, and install nvidia-docker2 to run the Dockerfile.

Obtaining file://House3D
Complete output from command python setup.py egg_info
running egg_info
creating House3D.egg-info
writing House3D.egg-info/PKG-INFO
writing dependency_links to House3D.egg-info/dependency_links.txt
wrirting top-level names to House3D.egg-info/top_level.txt
writing manifest file 'House3D.egg-info/SROUCES.txt'
error: package directory 'find:              # will call find_packages()' does not exist

Command "python setup.py egg_info" failed with error code 1 in /House3D/

**Comment by ppwwyyxx** [comment]
Thanks for reporting. This is an issue with latest version of pip & setuptools. It should be fixed now!
