### ISSUE TITLE
Have you implemented baseline for House3D

### ISSUE THREAD

**Issue by ZhuFengdaaa** [facebookresearch/House3D#40]
Do you have reinforcement learning baseline for for navigation task in House3D, like A3C, A2C or DDPG ?

**Comment by ppwwyyxx** [comment]
Unfortunately no. This project will only contain the environment.

**Comment by ZhuFengdaaa** [comment]
Thanks for notification. I am seeking for a solid baseline for navigation in House3D. It is strange that no baseline is released in such a active area. 

Is anybody here would like to share information about that? Thanks.

**Comment by mfe7** [comment]
@ppwwyyxx Is there a reason there is no baseline released? Even just a pre-trained model would be incredibly helpful and would encourage further use of this great simulator!
