### ISSUE TITLE
error while running Dockerfile

### ISSUE THREAD

**Issue by wwwqqqqq** [facebookresearch/House3D#45]
hi, I've just run the Dockerfile in ubuntu 14.04 system with nvida gpu, and got following error in the terminal:

### 
[dep]test-rectangle.cpp ...
Packge gl was not found in the pkg-config serach path.
Perhaps you should add the directory  containing 'gl.pc' to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Packge egl was not found in the pkg-config serach path.
Perhaps you should add the directory  containing 'egl.pc' to the PKG_CONFIG_PATH environment variable
No package 'x11' found
Packge x11 was not found in the pkg-config serach path.
Perhaps you should add the directory  containing 'x11.pc' to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[dep]objvie-offline.cpp ...
Packge gl was not found in the pkg-config serach path.
Perhaps you should add the directory  containing 'gl.pc' to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Packge egl was not found in the pkg-config serach path.
Perhaps you should add the directory  containing 'egl.pc' to the PKG_CONFIG_PATH environment variable
No package 'x11' found
Packge x11 was not found in the pkg-config serach path.
Perhaps you should add the directory  containing 'x11.pc' to the PKG_CONFIG_PATH environment variable
No package 'x11' found
...
### 
 I already installed opencv and related libraries, and the 'gl.pc', 'egl.pc', 'x11.pc' these files have been copied to the pkg-config serach path. Still it reports these error.
Thanks in advance

**Comment by ppwwyyxx** [comment]
> hi, I've just run the Dockerfile in ubuntu 14.04 system with nvida gpu

That's not true because the dockerfile does not use ubuntu 14.04. Please use our Dockerfile and run it with docker.

**Comment by wwwqqqqq** [comment]
root@lqx-Super-Server: /home/wtt/Desktop/House3D-masterroot@lqx-Super-Server:/home/wtt/Desktop/House3D-master# docker build test
Sending build context to Docker daemon  557.1kB
Sending build context to Docker daemon  3.542MB


Step 1/14 : FROM nvidia/opengl:1.0-glvnd-devel-ubuntu18.04
 ---> 04c47f164887
Step 2/14 : MAINTAINER Yuxin Wu
 ---> Using cache
 ---> aabd0231b367
Step 3/14 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 2bfbc8cc63cd
Step 4/14 : RUN apt-get update && apt-get install -y 	libglfw3-dev libglm-dev libx11-dev libegl1-mesa-dev 	libpng-dev libjpeg-dev python3-opencv 	python3-dev build-essential pkg-config git curl wget automake libtool
 ---> Using cache
 ---> 312d9dd2fbfb
Step 5/14 : RUN curl -fSsL -O https://bootstrap.pypa.io/get-pip.py && 	python3 get-pip.py && 	rm get-pip.py
 ---> Using cache
 ---> 993a6a297753
Step 6/14 : RUN pip3 install tqdm
 ---> Using cache
 ---> 0465c6826665
Step 7/14 : RUN git clone --recursive https://github.com/facebookresearch/House3D /House3D
 ---> Using cache
 ---> 4abf4b42a9ac
Step 8/14 : RUN wget https://github.com/facebookresearch/House3D/releases/download/example-data/example-data.tgz  -O /House3D/data.tgz && cd /House3D && tar xzf data.tgz
 ---> Using cache
 ---> 66fec6e9dbf7
Step 9/14 : ENV TEST_HOUSE /House3D/house/05cac5f7fdd5f8138234164e76a97383/house.obj
 ---> Using cache
 ---> e1c927ac8ad5
Step 10/14 : WORKDIR /House3D/renderer
 ---> Using cache
 ---> 261bebf2560a
Step 11/14 : ENV PYTHON_CONFIG python-config
 ---> Using cache
 ---> aa749d346352
Step 12/14 : RUN make -j
 ---> Running in bdbd3f66f3ef
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] objview-suncg.cpp ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] objview.cpp ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] test-rectangle.cpp ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] objview-offline.cpp ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] suncg/scene.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] suncg/render.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] vendor/tiny_obj_loader.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] rectangle/scene.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] model/scene.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] model/obj.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] model/mesh.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] model/shader.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] gl/camera.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] gl/utils.cc ...
[dep] gl/glContext.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] lib/debugutils.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] lib/timer.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] lib/strutils.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[dep] lib/imgproc.cc ...
[dep] lib/imgio.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] lib/imgio.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] lib/imgproc.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] lib/strutils.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] lib/timer.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] lib/debugutils.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] gl/glContext.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] gl/utils.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] gl/camera.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] model/shader.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] model/mesh.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] model/obj.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] model/scene.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] rectangle/scene.cc ...
[cc] vendor/tiny_obj_loader.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] suncg/render.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cc] suncg/scene.cc ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cpp] objview-offline.cpp ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cpp] test-rectangle.cpp ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[cpp] objview.cpp ...
[91mPackage gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package egl was not found in the pkg-config search path.
Perhaps you should add the directory containing `egl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'egl' found
Package x11 was not found in the pkg-config search path.
Perhaps you should add the directory containing `x11.pc'
to the PKG_CONFIG_PATH environment variable
No package 'x11' found
[0m[91mIn file included from gl/glContext.cc:9:0:
gl/api.hh:27:10: fatal error: X11/Xutil.h: No such file or directory
 #include <X11/Xutil.h>
          ^~~~~~~~~~~~~
compilation terminated.
[0m[91mmake: *** [build/gl/glContext.o] Error 1
make: *** Waiting for unfinished jobs....
[0mMakefile:61: recipe for target 'build/gl/glContext.o' failed
[cpp] objview-suncg.cpp ...
[91mIn file included from gl/glContext.hh:11:0,
                 from test-rectangle.cpp:9:
gl/api.hh:27:10: fatal error: X11/Xutil.h: No such file or directory
 #include <X11/Xutil.h>
          ^~~~~~~~~~~~~
compilation terminated.
[0m[91mmake: *** [build/test-rectangle.o] Error 1
[0mMakefile:65: recipe for target 'build/test-rectangle.o' failed
[91mIn file included from gl/glContext.hh:11:0,
                 from objview-suncg.cpp:13:
gl/api.hh:27:10: fatal error: X11/Xutil.h: No such file or directory
 #include <X11/Xutil.h>
          ^~~~~~~~~~~~~
compilation terminated.
[0mMakefile:65: recipe for target 'build/objview-suncg.o' failed
[91mmake: *** [build/objview-suncg.o] Error 1
[0m[91mIn file included from gl/glContext.hh:11:0,
                 from objview.cpp:13:
gl/api.hh:27:10: fatal error: X11/Xutil.h: No such file or directory
 #include <X11/Xutil.h>
          ^~~~~~~~~~~~~
compilation terminated.
[0mMakefile:65: recipe for target 'build/objview.o' failed
[91mmake: *** [build/objview.o] Error 1
[0m[91mIn file included from gl/glContext.hh:11:0,
                 from objview-offline.cpp:15:
gl/api.hh:27:10: fatal error: X11/Xutil.h: No such file or directory
 #include <X11/Xutil.h>
          ^~~~~~~~~~~~~
compilation terminated.
[0m[91mmake: *** [build/objview-offline.o] Error 1
[0mMakefile:65: recipe for target 'build/objview-offline.o' failed
[91mIn file included from ./gl/glContext.hh:11:0,
                 from suncg/render.hh:20,
                 from suncg/render.cc:8:
./gl/api.hh:27:10: fatal error: X11/Xutil.h: No such file or directory
 #include <X11/Xutil.h>
          ^~~~~~~~~~~~~
compilation terminated.
[0m[91mmake: *** [build/suncg/render.o] Error 1
[0mMakefile:61: recipe for target 'build/suncg/render.o' failed
The command '/bin/sh -c make -j' returned a non-zero code: 2

**Comment by ppwwyyxx** [comment]
Your error suggests that the command
```apt-get install -y libglfw3-dev libglm-dev libx11-dev libegl1-mesa-dev libpng-dev libjpeg-dev python3-opencv python3-dev build-essential pkg-config git curl wget automake libtool``` does not run correctly. Please clear your docker cache so that all commands will get executed.

Also, `docker build test` is not the right command because it gives `unable to prepare context: path "test" not found`

**Comment by ppwwyyxx** [comment]
Closing as there is no response.
