### ISSUE TITLE
Suggested addition to Instruction.md

### ISSUE THREAD

**Issue by mfe7** [facebookresearch/House3D#49]
Thanks for providing the Dockerfile - super convenient to use instead of compiling and installing the code. I suggest you add some more details of how to use the dockerfile in the `Instruction.md` file, since it is not crystal clear currently:

To build the docker img:
```
docker build -t house_3d:v0 .
```

Here is the command I used to run the docker container w/ GUI forwarding and mounting of my external drive that holds the SUNCG objects:
```
nvidia-docker run -it --name house_3d_instance --env="DISPLAY" --env="QT_X11_NO_MITSHM=1" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" -v /mnt/ubuntu_extra_ssd:/mnt/ubuntu_extra_ssd house_3d:v0
```

Then, you can test the code using:
```
python3 tests/test-rendering.py --interactive /mnt/ubuntu_extra_ssd/SUNCG/house/05cac5f7fdd5f8138234164e76a97383/house.obj
```

If everything is working, a window should pop up with a bunch of green (blank space) and a fenced house with a car and basketball hoop in the driveway (assuming you grabbed the example asset from the `Instruction.md`):
![house3d](https://user-images.githubusercontent.com/3514533/48026890-5a478700-e115-11e8-9f76-1384be8e3423.png)

You can use the keyboard to move the camera view around and on each step it should cycle between RGB, Semantic Label, Semantic Instance Label, and Depth image.

**Comment by ionvision** [comment]
This is really helpful, thanks much! @mfe7
