### ISSUE TITLE
Floor/walls not rendered, camera only rotates in test-env.py

### ISSUE THREAD

**Issue by mfe7** [facebookresearch/House3D#50]
I am using the provided Dockerfile and running `test-env.py` on house `0a0b9b45a1db29832dd84e80c1347854`

1. Why aren't the walls/floors being rendered properly, but everything else is?
![screenshot from 2018-11-05 18-31-33](https://user-images.githubusercontent.com/3514533/48033380-20807b80-e129-11e8-9fec-49d658930992.png)

2. I am running `test-env.py` and the camera rotates when I press `h` or `l` but doesn't move when I use `wasd`.

**Comment by mfe7** [comment]
Here is the terminal output for `test-env.py`:

```
root@1ec6790de550:/House3D/tests# cd /House3D/tests && python3 test-env.py
Data Loading ...
>> Default Target Room Type Selected = kitchen
  --> Done! Elapsed = 0.05s
Generating Low Resolution Obstacle Map ...
  --> Done! Elapsed = 0.01s
Generate High Resolution Obstacle Map (For Collision Check) ...
  --> Done! Elapsed = 0.01s
Generate Movability Map ...
  --> Done! Elapsed = 91.16s
Generate Target connectivity Map (Default <kitchen>) ...
[House] Caching New ConnMap for Target <kitchen>! (total 1 rooms involved)
WARNING!!!! [House] <find components in Target Room [kitchen]> No Open Components Found!!!! Return Largest Instead!!!!
 >>>> ConnMap Cached!
  --> Done! Elapsed = 4.02s
Generate Room Type Map ...
  --> Done! Elapsed = 1.58s
[split_shapes_by_material@obj.cc:167] Split shapes by material: 64 -> 165
# of vertices  = 69527
# of normals   = 69527
# of texcoords = 43717
# of materials = 103
# of shapes    = 165

(aaa:275): dbind-WARNING **: 20:51:01.416: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-Z30qzMwtxi: Connection refused
Gtk-Message: 20:51:01.432: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:51:01.433: Failed to load module "canberra-gtk-module"
```

**Comment by ppwwyyxx** [comment]
Hi,
I cannot reproduce your issue. When I test this house, the walls are correctly rendered.
I'm not sure what's going on. Could you perhaps open the house obj file with other obj file viewer (e.g. meshlab) and make sure that your obj file actually do have those walls? 

> I am running test-env.py and the camera rotates when I press h or l but doesn't move when I use wasd.

This is because the agent was not set to indoor areas and is therefore not allowed to move. You can call `env.reset` to put it to a random indoor location. I'll add this to the test script to avoid confusions.

**Comment by mfe7** [comment]
Thanks for the suggestion - the walls are also missing when I open the `house.obj` in meshlab, so the problem is not with this renderer.

I used the command: `gaps/bin/x86_64/scn2scn house.json house.obj` as suggested in the SUNCG toolbox repo you've linked in the instructions - any idea why that would miss walls/floors? I will do some digging as well.

Thank you for the info regarding `env.reset`!

**Comment by ppwwyyxx** [comment]
I used the same command to generate the obj, but that's a long time ago. Perhaps the SUNCG toolbox has introduced some bugs recently?

**Comment by mfe7** [comment]
Cool - the walls do indeed show up if I use `v1` of the suncg dataset, but not with `v2.1` so it's likely a recent issue with that toolbox. I created an issue on their toolbox, but might be helpful to let users of this repo know to use `v1` in the meantime. Thank you!
