### ISSUE TITLE
test-rendering.py error: ERROR::FRAMEBUFFER: Framebuffer is not complete! ErrorCode=36061

### ISSUE THREAD

**Issue by zzha5029** [facebookresearch/House3D#55]
I run the test-rendering.py (it seems not use the multi-thread rendering?) to generate one house only and appear this problem <error: ERROR::FRAMEBUFFER: Framebuffer is not complete! ErrorCode=36061>. Is that because my CPU memory is not big enough? I first test on my desktop rather than server and my CPU memory is only 32G. How much CPU memory should the test file consume?
look forward to your reply ^_^
my command in terminal is **python3 test-rendering.py ../house/05cac5f7fdd5f8138234164e76a97383/house.obj**
and return **error: ERROR::FRAMEBUFFER: Framebuffer is not complete! ErrorCode=36061**

**Comment by ppwwyyxx** [comment]
Please provide the details following the [trouble shooting guide](https://github.com/facebookresearch/House3D/tree/master/renderer#trouble-shooting).
