### ISSUE TITLE
error: ERROR::FRAMEBUFFER: Framebuffer is not complete! ErrorCode=36061

### ISSUE THREAD

**Issue by weihaosky** [facebookresearch/House3D#58]
I am using the docker to run House3D so I guess there is no build issues. When I run `python3 test-rendering.py $TEST_HOUSE` or  `./renderer/test-rectangle.bin headless` the error `error: ERROR::FRAMEBUFFER: Framebuffer is not complete! ErrorCode=36061` occur.

The output of `./debug-build.sh` is as follow:

```
PATH:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

CPATH:


PKG_CONFIG_PATH:


LIBRARY_PATH:


LD_LIBRARY_PATH:
/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64

PYTHONPATH:


ldconfig:
	libEGL_nvidia.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.0
	libEGL_nvidia.so.0 (libc6) => /usr/lib/i386-linux-gnu/libEGL_nvidia.so.0
	libEGL_mesa.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0
	libEGL_mesa.so.0 (libc6) => /usr/lib/i386-linux-gnu/libEGL_mesa.so.0
	libEGL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libEGL.so.1
	libEGL.so.1 (libc6) => /usr/lib/i386-linux-gnu/libEGL.so.1
	libEGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libEGL.so
	libEGL.so (libc6) => /usr/lib/i386-linux-gnu/libEGL.so
+ pkg-config --cflags --libs glfw3
-lglfw
+ '[' '!' '' ']'
+ pkg-config --cflags --libs libglvnd

+ pkg-config --cflags --libs egl
-I/usr/include/libdrm -lEGL
+ which find
/usr/bin/find
+ which pkg-config
/usr/bin/pkg-config
+ which python3-config
/usr/bin/python3-config
+ python3-config --includes --ldflags
-I/usr/include/python3.6m -I/usr/include/python3.6m
-L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/usr/lib -lpython3.6m -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
+ '[' ']'
+ g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ '[' -f ../House3D/objrender.so ']'
+ '[' -f objview.bin ']
```
The output of `./test-rectangle.bin egl` is :
```
[EGL] Detected 1 devices. Using device 0
----------- OpenGL Context Info --------------
GL Version: 4.5.0 NVIDIA 384.130
GLSL Version: 4.50 NVIDIA
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

```
The output of `./test-rectangle.bin headless` is:
```
----------- OpenGL Context Info --------------
GL Version: 3.3.0 NVIDIA 384.130
GLSL Version: 3.30 NVIDIA via Cg compiler
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1060 6GB/PCIe/SSE2
----------------------------------------------
error: ERROR::FRAMEBUFFER: Framebuffer is not complete! ErrorCode=36061

```

Many thanks!

**Comment by ppwwyyxx** [comment]
It looks like egl is actually working for you (`test-rectangle.bin egl` should produce an output image), but you have the `DISPLAY` environment variable so the renderer chooses the glx backend.
`unset DISPLAY` should fix `test-rendering.py` for you.

**Comment by weihaosky** [comment]
Thanks for reply! It works without GUI after I `unset DISPLAY`. But then any GUI cannot be run in the docker. Thus the interactive mode cannot be run.

**Comment by ppwwyyxx** [comment]
Can you run other GUI applications before `unset DISPLAY`?
I don't know why in this case GLX does not work for you: running X applications (especially those with opengl) under docker or ssh has always been quite tricky.

**Comment by weihaosky** [comment]
The same. Other GUI can run before `unset DISPLAY` but cannot run after `unset DISPLAY`. I have tried your docker in 2 different computers. The results are the same.

**Comment by trhuang97** [comment]
> It looks like egl is actually working for you (`test-rectangle.bin egl` should produce an output image), but you have the `DISPLAY` environment variable so the renderer chooses the glx backend.
> `unset DISPLAY` should fix `test-rendering.py` for you.

after i use  `unset DISPLAY`,how can i reset it?

**Comment by ppwwyyxx** [comment]
You can just open a new terminal or doing something equivalent to that. See some linux tutorial for details (e.g. https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps

**Comment by trhuang97** [comment]
Your solution has helped me.
Thank you very much!

Yuxin Wu <notifications@github.com> 于2019年7月21日周日 下午3:46写道：

**Comment by trhuang97** [comment]
hello,
Thank you for your help, and I don't know how to organize suncg's data
after donwload it. Need I move 'room' folder to 'house' folder? How to
organize texture,object and object_vox folder? What's TEST_HOUSE mean? Can
you give me some examples?
Thank you very much!

Yuxin Wu <notifications@github.com> 于2019年7月21日周日 下午3:46写道：

**Comment by ppwwyyxx** [comment]
With the latest commit, you can also run House3D with `DISPLAY` set, but `HOUSE3D_FORCE_EGL=1`. This will allow you to run House3D with EGL backend together with other applications that need `DISPLAY` (e.g., opencv)

**Comment by trhuang97** [comment]
where could I set HOUSE3D_FORCE_EGL?

Yuxin Wu <notifications@github.com> 于2019年7月24日周三 上午1:31写道：

**Comment by ppwwyyxx** [comment]
It's an environment variable. See some linux tutorial for details (e.g. https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps

**Comment by trhuang97** [comment]
but error still occur after 'export HOUSE3D_FORCE_EGL=1'

Yuxin Wu <notifications@github.com> 于2019年7月24日周三 上午1:50写道：

**Comment by ppwwyyxx** [comment]
Then please post issue following the [troubleshooting guide](https://github.com/facebookresearch/House3D/tree/master/renderer#trouble-shooting).
