### ISSUE TITLE
meet error when execute test-rending.py 

### ISSUE THREAD

**Issue by trhuang97** [facebookresearch/House3D#60]
when i test test-rending.py i count a error: ERROR::FRAMEBUFFER: Framebuffer is not complete! ErrorCode=36061
so i unset display
i meet another error:
error: Cannot connect to DISPLAY!
how could i solve it?

**Comment by ppwwyyxx** [comment]
For any build issues / installation issues, please include details following our  [trouble shooting guide](https://github.com/facebookresearch/House3D/tree/master/renderer#trouble-shooting).
