### ISSUE TITLE
how to organize suncg data?

### ISSUE THREAD

**Issue by trhuang97** [facebookresearch/House3D#61]
I don't know how to organize suncg's data after donwload it. Need I move 'room' folder to 'house' folder? How to organize texture,object and object_vox folder? What's TEST_HOUSE mean? Can you give me some examples?

**Comment by ppwwyyxx** [comment]
Hi,

"house/, object/, object_vox/, room/, texture/" should be organized together at the same level.

TEST_HOUSE means the full path to a `house.obj` file.

**Comment by trhuang97** [comment]
Thank you very much for your help!

Yuxin Wu <notifications@github.com> 于2019年7月23日周二 上午3:10写道：

**Comment by trhuang97** [comment]
Hello,thank you for your help but I also have a problem:
when I execute test-rendering.py, I meet error:error: ERROR::FRAMEBUFFER:
Framebuffer is not complete! ErrorCode=36061
1.Nvidia GTX 1080Ti,Ubuntu16.04;
2.I build by docker;
3.When I execute cd /House3D/tests && python3 test-rendering.py $TEST_HOUSE
--interactive,Error occur:ERROR::FRAMEBUFFER: Framebuffer is not complete!
ErrorCode=36061;
And i find error occur when it execute "api = objrender.RenderAPI(w=600,
h=450, device=0)"(ln13)
4.after i execute debug-build.sh,result:
PATH:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

CPATH:


PKG_CONFIG_PATH:


LIBRARY_PATH:


LD_LIBRARY_PATH:
/usr/lib/x86_64-linux-gnu:/usr/lib/i386-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64

PYTHONPATH:

DISPLAY:
:0

ldconfig:
libEGL_nvidia.so.0 (libc6,x86-64) =>
/usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.0
libEGL_nvidia.so.0 (libc6) => /usr/lib/i386-linux-gnu/libEGL_nvidia.so.0
libEGL_mesa.so.0 (libc6,x86-64) =>
/usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0
libEGL_mesa.so.0 (libc6) => /usr/lib/i386-linux-gnu/libEGL_mesa.so.0
libEGL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libEGL.so.1
libEGL.so.1 (libc6) => /usr/lib/i386-linux-gnu/libEGL.so.1
libEGL.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libEGL.so
libEGL.so (libc6) => /usr/lib/i386-linux-gnu/libEGL.so
+ pkg-config --cflags --libs glfw3
-lglfw
+ '[' '!' '' ']'
+ pkg-config --cflags --libs libglvnd

+ pkg-config --cflags --libs egl
-I/usr/include/libdrm -lEGL
+ which find
/usr/bin/find
+ which pkg-config
/usr/bin/pkg-config
+ which python3-config
/usr/bin/python3-config
+ python3-config --includes --ldflags
-I/usr/include/python3.6m -I/usr/include/python3.6m
-L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/usr/lib -lpython3.6m
-lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1
-Wl,-Bsymbolic-functions
+ '[' ']'
+ g++ --version
g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

+ '[' -f ../House3D/objrender.so ']'
+ ldd ../House3D/objrender.so
linux-vdso.so.1 (0x00007ffc6c9dd000)
libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f852d3f4000)
libEGL.so.1 => /usr/lib/x86_64-linux-gnu/libEGL.so.1 (0x00007f852d1e0000)
libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f852cea8000)
libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16
(0x00007f852cc76000)
libglfw.so.3 => /usr/lib/x86_64-linux-gnu/libglfw.so.3 (0x00007f852ca59000)
libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f852c7f1000)
libpython3.6m.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0
(0x00007f852c13f000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
(0x00007f852bf20000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(0x00007f852bb97000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f852b7f9000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f852b5e1000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f852b1f0000)
/lib64/ld-linux-x86-64.so.2 (0x00007f852d984000)
libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f852afbf000)
libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0
(0x00007f852ad09000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f852ab05000)
libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f852a8dd000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f852a6c0000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f852a4b8000)
libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2
(0x00007f852a2ad000)
libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1
(0x00007f852a0aa000)
libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1
(0x00007f8529ea4000)
libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1
(0x00007f8529c9a000)
libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f8529a68000)
libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f8529865000)
libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f8529661000)
libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6
(0x00007f852945b000)
libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f8529249000)
libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1
(0x00007f852903f000)
libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3
(0x00007f8528e39000)
libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f8528c24000)


Wish u lots of luck!

Yuxin Wu <notifications@github.com> 于2019年7月23日周二 上午3:10写道：
