### ISSUE TITLE
Docker Error: The command '/bin/sh -c /install/install_pip_packages.sh' returned a non-zero code: 1 ERROR: docker build failed. Dockerfile is at /home/ksu/tensorflow/tensorflow/tools/ci_build/Dockerfile.pi-python3

### ISSUE THREAD

**Issue by ernst-fanfan** [facebookresearch/House3D#64]
I need to install tensorflow 2.0 on a RASBERYPI. I keep running into this persistent error: The command '/bin/sh -c /install/install_pip_packages.sh' returned a non-zero code: 1
ERROR: docker build failed. Dockerfile is at /home/ksu/tensorflow/tensorflow/tools/ci_build/Dockerfile.pi-python3

please help

**Comment by ppwwyyxx** [comment]
unrelated to this project.
