### ISSUE TITLE
Link broken in INSTRUCTIONS.md

### ISSUE THREAD

**Issue by prass-anyvision** [facebookresearch/House3D#65]
Link for the creation of obj and ml files in the SUNCG toolbox is broken on the INSTRUCTIONS.md page : https://github.com/facebookresearch/House3D/blob/master/INSTRUCTION.md

It points to : https://github.com/shurans/SUNCGtoolbox#convert-to-objmtl

Do you perhaps have another instruction page to point out what the steps are?

**Comment by ppwwyyxx** [comment]
Unfortunately the toolbox was removed by its authors. Maybe you can find some copies of it elsewhere but we cannot help much about it.
